### ISSUE TITLE
拉取答案失败导致脚本退出

### ISSUE THREAD

**Issue by Charlizsz** [ufec/youxueyuan#1]
优学院更新了后台代码，导致原脚本无法拉取答案。根据抓包发现接口新加了一个parentID，请问能否修复？

**Comment by ufec** [comment]
我已经改好了，忘记发了

**Comment by Charlizsz** [comment]
碍于水平限制无法自己修改只能找到问题，如已改好，烦请更新到github。实在感谢，麻烦您了。

**Comment by ufec** [comment]
OK了，已经更新

**Comment by Charlizsz** [comment]
感谢无私贡献 已送star
